// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASgfnpEKtQ-6V_2AbY7gAccgcjbpGstuA',
    appId: '1:792688920980:web:fe596e1bedda36a6fee781',
    messagingSenderId: '792688920980',
    projectId: 'ecommerceapp-256ec',
    authDomain: 'ecommerceapp-256ec.firebaseapp.com',
    storageBucket: 'ecommerceapp-256ec.firebasestorage.app',
    measurementId: 'G-H1E2QM79D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRkkN6GwVgsrj-2zoXg8OqXSwi7oNJKt4',
    appId: '1:792688920980:android:2875c5ff369e4ec9fee781',
    messagingSenderId: '792688920980',
    projectId: 'ecommerceapp-256ec',
    storageBucket: 'ecommerceapp-256ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANXHESlO0YmD0lBcsRfiiM8UTjPR-TyI4',
    appId: '1:792688920980:ios:02feb6bd6e3abc76fee781',
    messagingSenderId: '792688920980',
    projectId: 'ecommerceapp-256ec',
    storageBucket: 'ecommerceapp-256ec.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANXHESlO0YmD0lBcsRfiiM8UTjPR-TyI4',
    appId: '1:792688920980:ios:02feb6bd6e3abc76fee781',
    messagingSenderId: '792688920980',
    projectId: 'ecommerceapp-256ec',
    storageBucket: 'ecommerceapp-256ec.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASgfnpEKtQ-6V_2AbY7gAccgcjbpGstuA',
    appId: '1:792688920980:web:f94707a8f5e3a7affee781',
    messagingSenderId: '792688920980',
    projectId: 'ecommerceapp-256ec',
    authDomain: 'ecommerceapp-256ec.firebaseapp.com',
    storageBucket: 'ecommerceapp-256ec.firebasestorage.app',
    measurementId: 'G-P44SKX9JJP',
  );
}
